[package]
name = "elixor"
version = "0.1.0"
edition = "2021"
authors = [ "skylix.net" ]
readme = "README.md"
license = "MIT"
description = "Elixor is a simple, fast, and secure framework for all aspects of programming."

exclude = [
    "target/",
    "scratches/"
]

[dependencies]
